import React, { useEffect, useMemo, useState } from 'react';
import { Form, Input, InputNumber, Modal, Select, message } from 'antd';
import { CalendarClock, DollarSign, Edit3, Globe2, Plus, Search, Target, Trash2, TrendingUp, UserRound } from 'lucide-react';
import { opportunityApi } from '../../services/api/index';
import type { Opportunity } from '../../services/api/index';

const stages=[{id:'new',label:'新商机',color:'bg-blue-500',probability:20},{id:'qualified',label:'需求确认',color:'bg-cyan-500',probability:40},{id:'proposal',label:'方案报价',color:'bg-amber-500',probability:65},{id:'negotiation',label:'商务谈判',color:'bg-violet-500',probability:85},{id:'won',label:'赢单',color:'bg-emerald-500',probability:100}];
const empty:Omit<Opportunity,'id'>={company:'',contact:'',email:'',country:'',product:'',value:0,probability:20,owner:'',nextFollowUp:null,stage:'new',source:'website',notes:''};
const OpportunitiesPage:React.FC=()=>{
  const [items,setItems]=useState<Opportunity[]>([]);const [loading,setLoading]=useState(true);const [keyword,setKeyword]=useState('');const [owner,setOwner]=useState('all');const [editing,setEditing]=useState<Opportunity|null|undefined>(undefined);const [form]=Form.useForm();
  const load=async()=>{setLoading(true);try{setItems(await opportunityApi.list());}catch{message.error('商机数据加载失败');}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
  const visible=useMemo(()=>items.filter(v=>(owner==='all'||v.owner===owner)&&`${v.company}${v.contact}${v.product}`.toLowerCase().includes(keyword.toLowerCase())),[items,owner,keyword]);
  const owners=[...new Set(items.map(v=>v.owner).filter(Boolean))];const total=items.filter(v=>v.stage!=='lost').reduce((s,v)=>s+Number(v.value),0);const forecast=items.reduce((s,v)=>s+Number(v.value)*v.probability/100,0);
  const openEditor=(item:Opportunity|null)=>{setEditing(item);form.setFieldsValue(item?{...item,nextFollowUp:item.nextFollowUp?.slice(0,16)}:empty);};
  const save=async()=>{const values=await form.validateFields();try{const payload={...empty,...values,nextFollowUp:values.nextFollowUp?new Date(values.nextFollowUp).toISOString():null};editing?await opportunityApi.update(editing.id,payload):await opportunityApi.create(payload);message.success(editing?'商机已更新':'商机已创建');setEditing(undefined);await load();}catch{message.error('商机保存失败');}};
  const move=async(item:Opportunity,stage:string)=>{const target=stages.find(v=>v.id===stage);const {id:_,...payload}=item;await opportunityApi.update(item.id,{...empty,...payload,stage,probability:target?.probability??item.probability});message.success(`已推进至${target?.label}`);await load();};
  const remove=(item:Opportunity)=>Modal.confirm({title:'删除商机',content:`确定删除 ${item.company} 的商机吗？`,okText:'删除',okButtonProps:{danger:true},cancelText:'取消',onOk:async()=>{await opportunityApi.remove(item.id);message.success('商机已删除');await load();}});
  return <div className="space-y-5"><div className="flex items-end justify-between"><div><h1 className="page-title">CRM 商机获取</h1><p className="page-subtitle">管理商机档案、负责人、预计金额与销售阶段，持续推进外贸成交</p></div><button onClick={()=>openEditor(null)} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white"><Plus size={15}/>新建商机</button></div>
  <div className="grid grid-cols-4 gap-4">{[{label:'商机总额',value:`$${total.toLocaleString()}`,icon:DollarSign,tone:'bg-violet-100 text-violet-700'},{label:'活跃商机',value:items.filter(v=>!['won','lost'].includes(v.stage)).length,icon:Target,tone:'bg-blue-100 text-blue-700'},{label:'加权预测',value:`$${Math.round(forecast).toLocaleString()}`,icon:TrendingUp,tone:'bg-emerald-100 text-emerald-700'},{label:'本周待跟进',value:items.filter(v=>v.nextFollowUp).length,icon:CalendarClock,tone:'bg-amber-100 text-amber-700'}].map(s=><div key={s.label} className="rounded-2xl border border-white/70 bg-white p-4 shadow-sm"><div className="flex justify-between"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${s.tone}`}><s.icon size={17}/></div><b className="text-2xl">{s.value}</b></div><p className="mt-3 text-xs font-semibold text-muted-foreground">{s.label}</p></div>)}</div>
  <div className="flex gap-2"><Input value={keyword} onChange={e=>setKeyword(e.target.value)} prefix={<Search size={14}/>} placeholder="搜索企业、联系人或产品" className="w-72"/><Select value={owner} onChange={setOwner} className="w-36" options={[{value:'all',label:'全部负责人'},...owners.map(v=>({value:v,label:v}))]}/><span className="self-center text-xs text-muted-foreground">{loading?'加载中…':`共 ${visible.length} 个商机`}</span></div>
  <div className="grid grid-cols-5 gap-3 overflow-x-auto">{stages.map(stage=>{const cards=visible.filter(v=>v.stage===stage.id);return <section key={stage.id} className="min-w-[210px] rounded-2xl bg-white/55 p-3"><header className="mb-3 flex justify-between"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${stage.color}`}/><b>{stage.label}</b><span className="rounded-full bg-white px-2 text-xs">{cards.length}</span></div><span className="text-xs text-muted-foreground">${cards.reduce((s,v)=>s+Number(v.value),0).toLocaleString()}</span></header><div className="space-y-3">{cards.map(card=><article key={card.id} className="rounded-xl border border-border bg-white p-4 shadow-sm"><div className="flex justify-between gap-2"><div><b>{card.company}</b><p className="mt-1 text-xs text-muted-foreground"><Globe2 size={12} className="mr-1 inline"/>{card.country||'未填写'} · {card.contact}</p></div><b className="text-primary">${Number(card.value).toLocaleString()}</b></div><div className="my-3 rounded-lg bg-secondary/50 px-3 py-2 text-xs">{card.product}</div><div className="mb-2 flex justify-between text-[11px] text-muted-foreground"><span>赢单概率 {card.probability}%</span><span>{card.owner}</span></div><div className="h-1.5 rounded-full bg-secondary"><div className={`h-full rounded-full ${stage.color}`} style={{width:`${card.probability}%`}}/></div><Select value={card.stage} onChange={value=>void move(card,value)} className="mt-3 w-full" size="small" options={stages.map(v=>({value:v.id,label:`推进至：${v.label}`}))}/><footer className="mt-3 flex items-center justify-between border-t border-border pt-3 text-[11px] text-muted-foreground"><span><UserRound size={12} className="mr-1 inline"/>{card.owner}</span><div className="flex"><button onClick={()=>openEditor(card)} className="p-1.5 hover:text-primary" title="编辑"><Edit3 size={13}/></button><button onClick={()=>remove(card)} className="p-1.5 hover:text-red-500" title="删除"><Trash2 size={13}/></button></div></footer></article>)}</div></section>})}</div>
  <Modal open={editing!==undefined} width={680} title={editing?'编辑商机':'新建商机'} onCancel={()=>setEditing(undefined)} onOk={save} okText="保存" cancelText="取消"><Form form={form} layout="vertical" className="pt-3"><div className="grid grid-cols-2 gap-x-3"><Form.Item name="company" label="企业名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="contact" label="联系人" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="email" label="邮箱" rules={[{type:'email'}]}><Input/></Form.Item><Form.Item name="country" label="国家/地区"><Input/></Form.Item><Form.Item name="product" label="意向产品" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="value" label="预计金额（USD）" rules={[{required:true}]}><InputNumber min={0} className="w-full"/></Form.Item><Form.Item name="owner" label="负责人" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="nextFollowUp" label="下次跟进"><Input type="datetime-local"/></Form.Item><Form.Item name="stage" label="销售阶段"><Select options={stages.map(v=>({value:v.id,label:v.label}))}/></Form.Item><Form.Item name="probability" label="赢单概率"><InputNumber min={0} max={100} addonAfter="%" className="w-full"/></Form.Item><Form.Item name="source" label="商机来源"><Select options={[{value:'website',label:'独立站询盘'},{value:'exhibition',label:'展会'},{value:'outreach',label:'开发信'},{value:'referral',label:'客户转介绍'}]}/></Form.Item></div><Form.Item name="notes" label="商机备注"><Input.TextArea rows={3}/></Form.Item></Form></Modal></div>;
};
export default OpportunitiesPage;
