import { MigrationInterface, QueryRunner, Table } from 'typeorm';
export class AddCustomersAndOpportunities1720935000000 implements MigrationInterface {
  async up(q: QueryRunner): Promise<void> {
    if (!(await q.hasTable('customers'))) await q.createTable(new Table({ name: 'customers', columns: [
      {name:'id',type:'varchar',length:'36',isPrimary:true},{name:'tenant_id',type:'varchar',length:'36'},{name:'site_id',type:'varchar',length:'36'},{name:'name',type:'varchar',length:'255'},{name:'company',type:'varchar',length:'255'},{name:'email',type:'varchar',length:'255',default:"''"},{name:'country',type:'varchar',length:'100',default:"''"},{name:'level',type:'varchar',length:'2',default:"'C'"},{name:'orders',type:'int',default:0},{name:'total_amount',type:'decimal',precision:14,scale:2,default:0},{name:'last_order_at',type:'date',isNullable:true},{name:'notes',type:'text',isNullable:true},{name:'created_at',type:'datetime',precision:6,default:'CURRENT_TIMESTAMP(6)'},{name:'updated_at',type:'datetime',precision:6,default:'CURRENT_TIMESTAMP(6)',onUpdate:'CURRENT_TIMESTAMP(6)'}], indices:[{name:'idx_customers_site',columnNames:['site_id']}] }));
    if (!(await q.hasTable('customer_level_rules'))) await q.createTable(new Table({ name:'customer_level_rules', columns:[{name:'id',type:'varchar',length:'36',isPrimary:true},{name:'tenant_id',type:'varchar',length:'36'},{name:'site_id',type:'varchar',length:'36'},{name:'code',type:'varchar',length:'2'},{name:'name',type:'varchar',length:'50'},{name:'min_amount',type:'decimal',precision:14,scale:2,default:0},{name:'min_orders',type:'int',default:0},{name:'sort',type:'int',default:0},{name:'updated_at',type:'datetime',precision:6,default:'CURRENT_TIMESTAMP(6)',onUpdate:'CURRENT_TIMESTAMP(6)'}],indices:[{name:'idx_level_rules_site',columnNames:['site_id']}] }));
    if (!(await q.hasTable('opportunities'))) await q.createTable(new Table({ name:'opportunities', columns:[{name:'id',type:'varchar',length:'36',isPrimary:true},{name:'tenant_id',type:'varchar',length:'36'},{name:'site_id',type:'varchar',length:'36'},{name:'company',type:'varchar',length:'255'},{name:'contact',type:'varchar',length:'255'},{name:'email',type:'varchar',length:'255',default:"''"},{name:'country',type:'varchar',length:'100',default:"''"},{name:'product',type:'varchar',length:'255'},{name:'value',type:'decimal',precision:14,scale:2,default:0},{name:'probability',type:'int',default:20},{name:'owner',type:'varchar',length:'100',default:"''"},{name:'next_follow_up',type:'datetime',isNullable:true},{name:'stage',type:'varchar',length:'30',default:"'new'"},{name:'source',type:'varchar',length:'30',default:"'website'"},{name:'notes',type:'text',isNullable:true},{name:'created_at',type:'datetime',precision:6,default:'CURRENT_TIMESTAMP(6)'},{name:'updated_at',type:'datetime',precision:6,default:'CURRENT_TIMESTAMP(6)',onUpdate:'CURRENT_TIMESTAMP(6)'}],indices:[{name:'idx_opportunities_site',columnNames:['site_id']}] }));
  }
  async down(q: QueryRunner): Promise<void> { for (const table of ['opportunities','customer_level_rules','customers']) if (await q.hasTable(table)) await q.dropTable(table); }
}
